# Generated by Django 3.2.6 on 2021-09-01 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=8)),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser status')),
            ],
        ),
        migrations.CreateModel(
            name='ITCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
              
                ('product_name', models.CharField(max_length=120)),
                ('product_brand', models.CharField(max_length=120)),
                ('serial_no', models.CharField(max_length=32)),
                ('model_no', models.CharField(max_length=18)),
                ('description', models.CharField(max_length=2000)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login1.itcategory')),
            ],
        ),
    ]
