# Generated by Django 3.2.6 on 2021-09-01 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=120)),
                ('product_brand', models.CharField(max_length=120)),
                ('serial_no', models.CharField(max_length=32)),
                ('model_no', models.CharField(max_length=18)),
                ('description', models.CharField(max_length=2000)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login1.itcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
