# Generated by Django 3.2.6 on 2021-09-02 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0003_alter_productdb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=200)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login1.itcategory')),
            ],
        ),
    ]
