# Generated by Django 3.2.6 on 2021-09-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0004_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='subcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login1.subcategory'),
        ),
    ]
