# Generated by Django 3.2.6 on 2021-09-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0005_productdb_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
