# Generated by Django 3.2.6 on 2021-09-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0006_alter_productdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
