# Generated by Django 3.2.6 on 2021-09-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0008_auto_20210902_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
