# Generated by Django 3.2.6 on 2021-09-03 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0009_remove_employee_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AlterField(
            model_name='productdb',
            name='category',
            field=models.ForeignKey(db_column='category_category', default='', on_delete=django.db.models.deletion.CASCADE, to='login1.itcategory'),
        ),
        migrations.AlterField(
            model_name='productdb',
            name='subcategory',
            field=models.ForeignKey(db_column='subcategoty_subcategory', default='', on_delete=django.db.models.deletion.CASCADE, to='login1.subcategory'),
        ),
    ]
