# Generated by Django 3.2.6 on 2021-09-03 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0010_auto_20210903_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login1.itcategory'),
        ),
        migrations.AlterField(
            model_name='productdb',
            name='subcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login1.subcategory'),
        ),
    ]
