# Generated by Django 3.2.6 on 2021-09-13 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0013_auto_20210913_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
